apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmarkservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmarkservice
  template:
    metadata:
      labels:
        app: studentmarkservice
    spec:
      containers:
        - name: studentmarkservice-container
          image: :
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
