apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - port: ${PORT}          # Service port (inside cluster)
      targetPort: ${PORT}    # Container port
      nodePort: ${NODE_PORT}     # Port accessible from Postman (your host)